name: Backend Tests
on: [push]
jobs:
  Backend-Tests:
    runs-on: ubuntu-latest
    services:
        mongodb:
            image: mongo
            options: >-
              --health-cmd mongo
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        working-directory: ./backend/
        run: npm install
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Run tests
        working-directory: ./backend/
        run: npm test