name: Backend Tests
on: [push]
jobs:
  Backend-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Open tests folder
        run: cd ${{ github.workspace }}/backend/tests
      - run: ls
      - run: npm install
      - name: Run tests
        run: npm test