name: Backend Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.workspace }}/backend/tests
      - run: ls
      - run: npm install
      - run: npm test