name: Backend Tests
on: [push]
jobs:
  Backend-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        working-directory: ./backend/
        run: npm install
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Run tests
        working-directory: ./backend/
        run: npm test