name: Backend Tests
on: [push]
jobs:
  Backend-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        working-directory: ./backend/
        run: npm install
      - name: Run tests
        working-directory: ./backend/test
        run: npm test